format = """
$hostname$directory$username$c$python$java$lua$rust$haskell
$character
"""

right_format = "$git_branch$git_commit$git_state$git_status"

palette = 'nord'

[hostname]
disabled = false
ssh_only = true
style = "bold warning"
format = "[$hostname]($style):"

[palettes.nord]
normal = '#aaaaaa'
lilac = '#b48ead'
danger = '#bf616a'
warning = '#d08770'
forest = '#a3be8c'
cerulean = '#8cafd2'
tiffany = '#8fbcbb'

[character]
success_symbol = "[â®‘](forest) "
error_symbol = "[â®‘](danger) "
vimcmd_symbol = "[â®‘](normal) "
vimcmd_replace_symbol = "[â®‘](cerulean) "
vimcmd_replace_one_symbol = "[â®‘](cerulean) "
vimcmd_visual_symbol = "[â®‘](lilac) "

[directory]
truncation_length = 2
truncation_symbol = "../"
truncate_to_repo = false
read_only = " ï€£"
read_only_style = "danger"
style = "blck"
format = "[$path]($style)[$read_only]($read_only_style) "

[status]
format   = '([\[$status\]](bold red) )'
disabled = false

[cmd_duration]
min_time          = 5_000
show_milliseconds = true
style             = 'normal'
format            = '([$duration]($style) )'

[git_commit]
style = "lilac"
format = "[\\($hash$tag\\)]($style)"

[username]
style_root = 'bold warning'
style_user = 'normal'
format     = '( [\($user\)]($style))'

[git_branch]
symbol = "ó°Š¢ "
style = "normal"
format = "[$symbol$branch]($style)"

[git_status]
ahead = "â‡¡${count}"
diverged = "â‡•â‡¡${ahead_count}â‡£${behind_count}"
behind = "â‡£${count}"
style = "bold lilac"
format = "([\\[$all_status$ahead_behind\\]]($style))"

[python]
format = '(via [$symbol$version \($virtualenv\)]($style))'
symbol = "îˆµ "

[aws]
symbol = "îŒ½  "
format = "via [$symbol$version]($style)"

[buf]
symbol = "ï’ "
format = "via [$symbol$version]($style)"

[c]
symbol = "î˜ "
format = "via [$symbol$version]($style)"

[conda]
symbol = "ï„Œ "
format = "via [$symbol$version]($style)"

[dart]
symbol = "î˜ "
format = "via [$symbol$version]($style)"

[docker_context]
symbol = "ïŒˆ "
format = "via [$symbol$version]($style)"

[elixir]
symbol = "î‰µ "
format = "via [$symbol$version]($style)"

[elm]
symbol = "î˜¬ "
format = "via [$symbol$version]($style)"

[golang]
symbol = "î˜§ "
format = "via [$symbol$version]($style)"

[guix_shell]
symbol = "ïŒ¥ "
format = "via [$symbol$version]($style)"

[haskell]
symbol = "î· "
format = "via [$symbol$version]($style)"

[haxe]
symbol = "âŒ˜ "
format = "via [$symbol$version]($style)"

[hg_branch]
symbol = "ï˜ "
format = "via [$symbol$version]($style)"

[java]
symbol = "î‰– "
format = "via [$symbol$version]($style)"

[julia]
symbol = "î˜¤ "
format = "via [$symbol$version]($style)"

[lua]
symbol = "î˜  "
format = "via [$symbol$version]($style)"

[memory_usage]
symbol = "ï¡š "

[meson]
symbol = "ï¨¶ "
format = "via [$symbol$version]($style)"

[nim]
symbol = "ïš¤ "
format = "via [$symbol$version]($style)"

[nix_shell]
symbol = "ïŒ“ "

[nodejs]
symbol = "îœ˜ "

[package]
symbol = "ï£– "

[rlang]
symbol = "ï³’ "

[ruby]
symbol = "î‘ "
format = "via [$symbol$version]($style)"

[rust]
symbol = "î¨ "
format = "via [$symbol$version]($style)"

[scala]
symbol = "îœ· "

[spack]
symbol = "ğŸ…¢ "

[os.symbols]
Alpine = "ïŒ€ "
Amazon = "ï‰° "
Android = "ï…» "
Arch = "ïŒƒ "
CentOS = "ïŒ„ "
Debian = "ïŒ† "
DragonFly = "îŠ "
Emscripten = "ïˆ… "
EndeavourOS = "ï†— "
Fedora = "ïŒŠ "
FreeBSD = "ïŒŒ "
Garuda = "ï¯‘ "
Gentoo = "ïŒ "
HardenedBSD = "ï²Š "
Illumos = "ïœ· "
Linux = "ïŒš "
Macos = "ïŒ‚ "
Manjaro = "ïŒ’ "
Mariner = "ï‡ "
MidnightBSD = "ï†† "
Mint = "ïŒ "
NetBSD = "ï€¤ "
NixOS = "ïŒ“ "
OpenBSD = "ïœ¹ "
openSUSE = "ïŒ” "
OracleLinux = "ï ¶ "
Pop = "îŠ£ "
Raspbian = "ïŒ• "
Redhat = "ïŒ– "
RedHatEnterprise = "ïŒ– "
Redox = "ï”— "
Solus = "ï´± "
SUSE = "ïŒ” "
Ubuntu = "ïŒ› "
Unknown = "ïˆ­ "
Windows = "ï¡± "
